spring:
  profiles:
    include: MYSQL
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gift?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false

#flyway
flyway:
  locations: classpath:db
  enabled: true
  sqlMigrationPrefix: v